### ISSUE TITLE
I tried to train faces use FFHQ and celebA dataset. Why is the image sampled in the training completely different from the input image face? When I input an image during the inference, the generated face is completely different from the input face.  And why domain_embed_scale=0.1  in training？   Thankyou！      

### ISSUE THREAD

**Issue by wangzhaolei** [mkshing/e4t-diffusion#13]

**Comment by Actis92** [comment]
For what concern the generated faces is completely different, I have noticed the same thing, and for now I don't know the cause. For what concern domain_embed_scale=0.1 is defined in the paper, it's the scaling factor
<img width="632" alt="Screenshot 2023-03-27 at 16 44 07" src="https://user-images.githubusercontent.com/46601193/227975286-fc4008b6-8e83-449a-ad8d-43f52a7cfaf7.png">

**Comment by mkshing** [comment]
I changed a lot of parts to get better results and released the pre-trained model for face. You should check the latest code and reopen this issue if you have still problems.
