### ISSUE TITLE
CUDA out of memory when running pretrain of branch v1 even if I set batch_size to 1. I wonder how much GPU memory is required to train this model. And does this mean I can't train on the V100(32G)?

### ISSUE THREAD

**Issue by dong-y21** [mkshing/e4t-diffusion#14]

**Comment by dong-y21** [comment]
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 accelerate launch pretrain_e4t.py \
  --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" \
  --clip_model_name_or_path="ViT-H-14::laion2b_s32b_b79k" \
  --domain_class_token="face" \
  --placeholder_token="*s" \
  --prompt_template="face" \
  --save_sample_prompt="a photo of the *s,a photo of the *s in monet style" \
  --reg_lambda=0.01 \
  --domain_embed_scale=0.1 \
  --output_dir="pretrained-face-FFHQ" \
  --train_image_dataset="FFHQ_CelebA-HQ" \
  --iterable_dataset \
  --resolution=512 \
  --train_batch_size=1 \
  --learning_rate=1e-6 --scale_lr \
  --checkpointing_steps=3000 \
  --log_steps=1000 \
  --max_train_steps=30000 \
  --unfreeze_clip_vision \
  --mixed_precision="fp16" \
  --enable_xformers_memory_efficient_attention

**Comment by mkshing** [comment]
You need >40GB for pre-training.

**Comment by blx0102** [comment]
@mkshing Hi, what about tuning? need > 40GB as well? I tried on my 3090 with 24GB, also got OOM error.

**Comment by mkshing** [comment]
@blx0102 Yes, domain-tuning also needs >40GB at least

**Comment by blx0102** [comment]
@mkshing Get it, thanks!
