### ISSUE TITLE
difference in the structure of encoder

### ISSUE THREAD

**Issue by XavierXiao** [mkshing/e4t-diffusion#3]
Hi! Thanks for the amazing implementation! One thing I notice is that in the paper, they mentioned 

>  Specifically, we extract the features of the [CLS] token of each 2nd CLIP layer as an hierarchical feature representation. Each such feature vector is fed through a linear layer, followed by average-pooling over the hierarchy and LeakyReLU activation

But if I understand correctly, you only use one layer of the CLIP image embedding? They said it should be every  2nd layer (i.e., 1, 3, 5, 7, ... layers)

In addition, it seems like your implementation will introduce weight offset to both cross-attention and self-attention blocks (because CrossAttention class will have the offsets by default), while the paper only does this on cross-attention.

**Comment by mkshing** [comment]
@XavierXiao Hi, thanks for your comment. 
For the hidden states of CLIP, you're right. I might miss "every". Will fix it soon. 
For the offsets, I think my implement is correct based on the following sentence. 
> We observe that the cross- and self-attention layers have higher
scores, indicating that they play a crucial part in the tuning effort,
and thus focus on modulating the weights of these layers.

**Comment by XavierXiao** [comment]
Thanks! Yeah it seems like they modify both self and cross-attention layers. I thought they only do cross attention.

**Comment by mkshing** [comment]
@XavierXiao I fixed the clip part in https://github.com/mkshing/e4t-diffusion/pull/4. Thank you!

**Comment by mkshing** [comment]
But, my previous implementation is definitely worth to try because I believe that part aims to extract the features of the domain and I feel mine is more straightforward. I am guessing that it's applied because of aligning with the fact that unet pooled features are extracted from each of its blocks.

**Comment by XavierXiao** [comment]
It worth trying! Although I think the intuition is that one layer (at the end) is only capturing high level information and not enough for the details. Similar idea (using ensemble of multiple CLIP layers) is used in this concurrent paper https://arxiv.org/pdf/2302.13848.pdf

**Comment by XavierXiao** [comment]
BTW can you explain [this line ](https://github.com/mkshing/e4t-diffusion/blob/main/e4t/models/cross_attention.py#L215)? I can understand the previous line which does the grad calculation, but unclear what this line does. Not super familiar woth the autograd. Thanks!
